### PR TITLE
feat: add DisableEvents option

### LINKED ISSUE #20: feature request: disable event collection
We would like to be able to disable event collection when using the FeatBit Server SDK for .NET.

https://github.com/featbit/featbit/issues/531 would also solve this, but is a bigger change.

If we could just construct a `FbClient` with a `NullEventProcessor` but keep the `WebSocketDataSynchronizer` that would solve it for us, but right now it's either fully online or fully offline.

The reason for this is just that we want to get flags into an existing system that is already under load and enable events after, starting with services that are under less load and would produce fewer events. We're primarily interested in flags and events are nice to have but add risk.

This could be done with an extra flag on the options (defaulting to current behaviour), for example.

It could also be done by using a different URI like `urn:featbit:null` which would not affect the API surface but is a bit less intuitive.

I'm happy to submit a pull request if needed.

### PR DESCRIPTION
**Pull request by ghelyar**
Adds an option to disable event collection but keep data synchronisation, defaulting to the current behaviour of both online.

Also fixes some incorrect test names.

resolves #20

### CODE REVIEW

**Comment by ghelyar** [comment]
Could someone please review this?
@deleteLater @cosmic-flood @cosmos-explorer

**Comment by cosmic-flood** [comment]
> Could someone please review this? @deleteLater @cosmic-flood @cosmos-explorer

Sorry, we missed this pull request. We will review it these days.

**Comment by deleteLater** [comment]
I will review this PR today

**Comment by deleteLater** [comment]
LGTM! Thanks @ghelyar ❤️

**Comment by deleteLater** [comment]
I've released version 1.2.2, which includes this feature.

**Comment by ghelyar** [comment]
Thanks 👍

**Pull request merged**
